package handlers

type WikisHandlers interface {
	AddTopic() error
	ScrapeIslandByAreaForTopics() error
	AutoGenerateTopics() error
	UpdateTopic() error
	DeleteTopic() error
	GetWikis() error
	StartWorker() error
	AutoGenerateDescWorker() error
}
